intent:
    volume:
        de:
            invalid_volume: ["Bitte nenne eine Lautstärke zwischen 0 und 10."]
            volume_up: "Lauter"
            volume_down: "Leiser"
        en:
            invalid_volume: ["Please set the volume between 0 and 10."]
            volume_up: "Volume up"
            volume_down: "Volume down"
            