assistant:
    language: "german"
    wakewords: ["bumblebee", "terminator"]
    allow_only_known_speakers: True
defaults:
    german:
        no_intent_recognized: ["Ich habe dich nicht verstanden", "Den Befehl habe ich nicht verstanden"]