assistant:
  language: de
  wakewords:
  - bumblebee
  - terminator
  allow_only_known_speakers: true
  volume: 0.6
  silenced_volume: 0.1
defaults:
  de:
    no_intent_recognized:
    - Ich habe dich nicht verstanden
    - Den Befehl habe ich nicht verstanden
