intent:
    smarthome:
        de:
            state_unknown: "Der Zustand {} ist f체r den Schalter ung체ltig."
            device_unknown: "Das Ger채t {} kenne ich nicht."
            on: ["an", "ein"]
            off: ["aus"]
        en:
            state_unknown: "The state {} is invalid."
            device_unknown: "The device {} is unknown."
            on: ["on"]
            off: ["off"]
        devices:  
            B체ro: "192.168.0.1"