intent:
    location:
        de:
            weatheris: ["Das Wetter in {} ist {} bei einer Temperatur von {} Grad Celsius."]
            location_not_found: "Ich konnte der Ort {} nicht finden."
        en:
            weatheris: ["The weather in {} is {} at a temperatur of {} degrees."]
            location_not_found: "I could not find a place called {}."
        owm_api_key: "9a68c78b517a402b4d6ea609b0c7beba"
            